import { Outfit } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import "animate.css";
import { Toaster } from "react-hot-toast";

const OutfitFont = Outfit({
  subsets: ["latin"],
});




export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${OutfitFont.className}  h-full antialiased`}
    >
      <body>
        <Navbar/>
        <main className="max-w-7xl mx-auto">{children} </main>
        <Footer/>
          <Toaster position="top-right" />
      </body>
    </html>
  );
}
